apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gitea
spec:
  descriptor:
    links:
      - description: Open Gitea
        # needs to match applicationUrl in kots-app.yaml
        url: "http://gitea"
