apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slackernews
  namespace: helmvm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
# needs values that are set in the slackernews-replicated HelmChart CR
spec:
  project: default
  source:
    chart: gitea-redux-spider/gitea 
    repoURL: registry.shortrib.io
    targetRevision: 0.3.2-replicated.5
    helm:
      values: |
        rootUrl: git.shortrib.dev
        exposeSSH: true 
        
        adminPassword: rightly-unduly-literally-main-cheetah
        adminEmail: crdant@shortrib.io

        postgresql:
          enabled: true

  destination:
    namespace: gitea
    server: https://raccoon.lab.shortrib.net:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
