{{- if .Values.global.replicated -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: replicated-registry 
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{- end -}}

